/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILES_H_RPCGEN
#define _FILES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define FILEPROG 0x20000010
#define FILEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SHOWDIR 1
extern  char ** showdir_1(char *, CLIENT *);
extern  char ** showdir_1_svc(char *, struct svc_req *);
extern int fileprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SHOWDIR 1
extern  char ** showdir_1();
extern  char ** showdir_1_svc();
extern int fileprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILES_H_RPCGEN */
